### PR TITLE
feat: add support for all plex image transcodes

### PR DESCRIPTION
**Pull request by Jabster28**
i'm not sure if i did this right, but it works when i built it manually 😅 
let me know if i need to change anything

### CODE REVIEW

**Comment by Jabster28** [comment]
there aren't really any sites you can test it on if you don't have a plex server (since all of plex's free movies have their own endpoint)

**Comment by qsniyg** [comment]
Thank you very much! Could you send me example URLs? It's alright if I can't access them, just so that I can have a sense of what the rule does :)

**Comment by Jabster28** [comment]
sure, that's fine! (warning that i'm not 100% sure of any of the info here, i just did a bunch of tests and this is what i perceived)

plex saves all of it's image data in the highest res possible, but it "transcodes" the images to a lower res while viewing them in the ui (to reduce required bandwidth, i assume), for example the artist page:

image

this causes the image link to be something like this:

```
https://url.plex.direct:32400/photo/:/transcode?width=720&height=720&minSize=1&upscale=1&url=%2Flibrary%2Fmetadata%2F15362%2Fthumb%2F1641679236%3FX-Plex-Token%3Dt0K3ng0Esh3rE
```

upon checking, you can see that the `url` query value `%2Flibrary%2Fmetadata%2F15362%2Fthumb%2F1641679236%3FX-Plex-Token%3Dt0K3ng0Esh3rE` is just a URL encoded version of `/library/metadata/15362/thumb/1641679236?X-Plex-Token=t0K3ng0Esh3rE`. going to that URL with the same domain (e.g. `https://url.plex.direct:32400/library/metadata/15362/thumb/1641679236?X-Plex-Token=t0K3ng0Esh3rE`) gives you the original file in the highest resolution.

hope that makes sense :)

**Comment by TheLastZombie** [comment]
Just tested it on my own installation, looks good!

**Comment by qsniyg** [comment]
Thanks @TheLastZombie ! I don't have a plex setup, so I was unable to test this.

**Pull request merged**
