### PR TITLE
Monthly automatic releases via GitHub Actions

### LINKED ISSUE #506: Make proper github releases
https://github.com/qsniyg/maxurl/issues/28#issuecomment-717748801

Probably containing crx, xpi, userscript, userscript_smaller

### LINKED ISSUE #1044: Firefox extension not updated
Hello

I was wondering if you had plans to update the extension that is on their extension store, or if you are only planning to release it on userscript moving forward. 

I know there is the option of sideloading the extension but since it seems it only works temporarily (until the app is closed) I was looking for a proper extension that could be installed.

Thanks.

### LINKED ISSUE #1048: Please do GH releases for the userscript
As the title says, can you please do releases for the userscript so we may get notified and update it manually?

### PR DESCRIPTION
**Pull request by TheLastZombie**
This PR tracks the automatic generation and publishing of monthly releases of all versions of the script, including:

- [x] The userscript on GitHub (push build, create tag),
- [ ] the userscript on OpenUserJS (send webhook),
- [ ] the extension on AMO and Opera add-ons,
- [x] the website hosted on GitHub Pages and
- [ ] the Reddit bot (pull and restart).

The following repository secrets need to be set up:

- [ ] `MAXURL_PEM` (contents of the `maxurl.pem` file)
- [ ] `API_KEY` (JWT issuer, see: [Manage API Keys](https://addons.mozilla.org/developers/addon/api/key/))
- [ ] `API_SECRET` (JWT secret, see: [Manage API Keys](https://addons.mozilla.org/developers/addon/api/key/))

This entire workflow also hasn't been tested yet.

Depending on the eventual implementation, this could fix #506, fix #1044 and fix #1048.

### CODE REVIEW

**Comment by Luke-L** [comment]
so does this mean the extensions/addons will be updated with new supported sites automatically every month?

**Comment by TheLastZombie** [comment]
That's the plan, yes.

**Comment by TheLastZombie** [comment]
I'm closing this PR now since updates have resumed and I haven't been working on it for a while now.

**Comment by qsniyg** [comment]
Thank you for your work on this. I've always been a little queasy about automatic releases (especially in light of the whole xz situation), so instead I've been working on automating the build process as much as possible so it isn't as much of a pain :)

**Pull request closed without merging**
